### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by lrlucena** [jroesch/language-scala#15]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (C:\Users\Lucena\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:550:9)
<unknown> (C:\Users\Lucena\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:172:43)
```

**Comment by laughedelic** [comment]
There is an issue with exactly the same title and even it is a duplicate: https://github.com/jroesch/language-scala/issues/14

**Comment by lrlucena** [comment]
Sorry. The issue was suggested by Atom. I will open an issue about suggesting duplicated issues in Atom repository.
