### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by btd** [jroesch/language-scala#16]
Hello, @jroesch.

It does not look like you interested in supporting this repo. Maybe you will add collaborators and share instructions to publish package?

Thanks.

**Comment by laughedelic** [comment]
:+1:

**Comment by btd** [comment]
Just if anybody interested i created a [fork](https://github.com/btd/language-scala-plus). I promise to fix all deprecations but do not promise create new features as free time quite limited. If you want to be collaborator feel free to ping me.

**Comment by gangstead** [comment]
@jroesch added me as a contributor and I'm doing my best to keep the project active with 3 patch releases in the last three days.  If you'd like to be a contributor I'd recommend emailing him through the email on his github profile, as I did.  His github notifications get drowned out by another project he contributes to, but he does take notice of the emails.
